### ISSUE TITLE
Copyright Dates Color Issues

### ISSUE THREAD

**Issue by Dracrius** [Masaru2/pokejp#2]
The first screen of the intro with the copyright dates show yellow and a nice rainbow for the last date and grey for the dates at the title. They should be all black but I have yet to find what caused the bug. I will attach two screen shots but it is consistent in Red, Green, and Blue. I originally thought it was changes I made but after doing a fresh pull of your repo and only fixing the two files to get it to build I still see the issue on yours before any of my changes to re implement the pocket monsters logo.  

![Dates Color Problem](https://user-images.githubusercontent.com/26284634/212168632-db250772-e565-4d67-9d21-3b31d29bfb73.png)
![Title Color Problem](https://user-images.githubusercontent.com/26284634/212168673-acb3b549-a742-4269-9d60-826a9466954c.png)

**Comment by Dracrius** [comment]
Found the issue and I sent in a second Pull Request with the fix for you!   Copyright Color Fix #4

**Comment by Masaru2** [comment]
I didn't knew I had that issue, it showed normal for me

**Comment by Dracrius** [comment]
Im guessing its caused by some changes in 0.6.1 vs 0.4.1 then since you said ud been using it.
